### PR TITLE
add missing int types (u)int16, uint32, uint64 to SSE and AVX

### PR DESCRIPTION
**Pull request by wolfv**
@serge-sans-paille it's slowly coming together... should be "ready" by tomorrow!

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
Cool!

Once merged, i'll check that with pythran :-)

**Comment by wolfv** [comment]
btw how many mixed loading facilities do you need? E.g. currently you can load a `int64` batch from a `int` pointer, or a `float` pointer etc.

I'll need to figure out the appropriate conversions for this though ...

**Comment by serge-sans-paille** [comment]
This kind of conversions are currently disabled in pythran, let's add
them later

**Comment by serge-sans-paille** [comment]
@wolfv there seems to be an issue with (at least) ``_mm_max_epu16``, see https://travis-ci.com/serge-sans-paille/pythran/jobs/144269427

**Comment by wolfv** [comment]
Will fix that!

**Comment by JohanMabille** [comment]
Let's merge it and fix the bugs that wil be found thanks to pythran integration in dedicated PRs.

**Pull request merged**
