### PR TITLE
WIP - Fixed flags for ppc architecture

### PR DESCRIPTION
**Pull request by JohanMabille**

### CODE REVIEW

**Comment by hroncok** [comment]
testing a build

**Comment by hroncok** [comment]
it builds

**Comment by JohanMabille** [comment]
Just to be sure, it builds on all the platform, so if I tag a new release, you will be able to package it for Fedora? Or are there other issues that I should fix before releasing?

**Comment by hroncok** [comment]
I've already backported both PRs and done the ARM workaround in Fedora. It builds on all our architectures.

**Comment by JohanMabille** [comment]
wonderfull!

**Pull request merged**
