### PR TITLE
Fix copysign implementation on windows

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
See https://ci.appveyor.com/project/serge-sans-paille/pythran/build/1.0.839 for the fail that spotted this « error »

**Comment by serge-sans-paille** [comment]
> Does it work if you #undef copysign before including xsimd?

Yeah, that looks like a #define from the ms header. I'm not #undef is an
option then, because it would propagagte to all files including xsimd.

**Comment by SylvainCorlay** [comment]
To prevent the macro expansion, would it work to put `copysign` in parentheses like we do for `max` and `min`. `(copysign)(x, y)`.

**Comment by serge-sans-paille** [comment]
the expansion is an issue in the original ``using std::copysign``, I don't think your trick would work. The travis build only needs to be restarted!

**Comment by SylvainCorlay** [comment]
I would think that the parentheses should be added around the function call. (In the macro for math functions).

**Comment by serge-sans-paille** [comment]
Which function call are you considering? The original statement is just

    using std::copysign;

**Comment by serge-sans-paille** [comment]
Culprint found: https://github.com/python/cpython/blob/master/PC/pyconfig.h#L193
So definitievly *not* an xsimd related error.

**Pull request closed without merging**
